### ISSUE TITLE
Getting error while running the script

### ISSUE THREAD

**Issue by mehranagh20** [hejazizo/us-visa-rescheduler#3]
Hi @hejazizo!
I get the following error while running the script:
`NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="header"]/nav/div[2]/div[1]/ul/li[3]/a"}`

Maybe they have changed some elements in their website? Any suggestions?

**Comment by sarathbp** [comment]
Ok.

**Comment by samanronagh** [comment]
> Hi @hejazizo! I get the following error while running the script: `NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="header"]/nav/div[2]/div[1]/ul/li[3]/a"}`
> 
> Maybe they have changed some elements in their website? Any suggestions?

Have had the same problem since yesterday...

**Comment by Demarsch** [comment]
Should be `//*[@id="header"]/nav/div/div/div[2]/div[1]/ul/li[3]/a` with latest page layout

**Comment by hejazizo** [comment]
Thanks @Demarsch. I updated the code base with your fix and it works. Next time you can also send a pull request and I'll merge it.

**Comment by Jeetpal1** [comment]
> Should be `//*[@id="header"]/nav/div/div/div[2]/div[1]/ul/li[3]/a` with latest page layout

Hey @Demarsch how did you find this? I am getting almost the same error but for the element class "down-arrow bounce", may be they updated it again. Could you guide? Or @hejazizo If you have an idea
![image](https://github.com/hejazizo/us-visa-rescheduler/assets/70360391/400df3ca-c3b2-48c1-b6b4-37e3fd37f82c)


Error after Login Successful and Searching for available date: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class="down-arrow bounce"]"}
  (Session info: chrome=123.0.6312.59)
![image](https://github.com/hejazizo/us-visa-rescheduler/assets/70360391/ecc19b00-5b87-4747-9eb0-1c054a899035)

**Comment by Demarsch** [comment]
@Jeetpal1 , not sure what exactly going on. Judging by the logs on your screen you should reach the point of `driver.find_element(by=By.ID, value='ui-datepicker-div')` and not look for the down-arrow bounce

**Comment by Jeetpal1** [comment]
@Demarsch Sorry, I am little confused, I don't think the current main.py (main branch) has any line of code where it is finding "ui-datepicker-div" id element. Do you have some updated code locally?

**Comment by Jeetpal1** [comment]
The problem seems to be here with this "continue" button clicking which was commented, but it still doesn't work because it is not being traced. 
We can try to 
![image](https://github.com/hejazizo/us-visa-rescheduler/assets/70360391/8620c880-09ae-43d6-96fe-d0c91e94fe53)


However, I think we should be able to access this "a" element using its class name which is "button primary small" (if the combination of these three classes is unique on this webpage) as below:
![image](https://github.com/hejazizo/us-visa-rescheduler/assets/70360391/f00ffefd-d3f4-4c5b-bc71-b9ec9ea85489)

**Comment by qlan3** [comment]
Hi, I got the same error. Any idea how to fix it?
